### ISSUE TITLE
Validation message does not display for checkboxlist form group

### ISSUE THREAD

**Issue by jimnorth55** [aurelia/templating-validation#8]
My template includes a form-group containing a list of checkbox elements all bound to a single model property [user.notifications] (string array), as shown below.

```
<div class="form-group">
	<label>Notifications</label>
	<ul>
		<li class="list-unstyled" repeat.for="notification of notifications">
			<div class="checkbox checkboxlist">
				<label>
					<input type="checkbox" value.bind="notification.key"
					    checked.bind="user.notifications"> ${notification.name}
				</label>
			</div>
		</li>
	</ul>
 </div>
```

A fluent validation rule is set for [user.notifications]  which requires at least one selection. 

When I try to submit the form with nothing selected, the call to validate() in my submit delegate is failing as expected, but no message is displayed next to the label tag.   I tried adding a "for" attribute to the label tag and this does not make a difference.

**Comment by EisenbergEffect** [comment]
No longer applicable based on the new validation architecture.
