### ISSUE TITLE
Bug - Aurelia’s Validation

### ISSUE THREAD

**Issue by ClareBear85** [aurelia/templating-validation#9]
\jspm_packages\npm\aurelia-validation@0.6.6\validation-property.js

“_this.validateCurrentValue(true);” Subscribed method, basically says “when one of the dependent values changes - call the validation method for this item”.

There is an optional parameter to tell it to “forceExecution” which needs setting we think. 

We believe the line should read “_this.validateCurrentValue(true, true);”. This then triggers the validation when one of the “computed” fields changes value.

**Comment by EisenbergEffect** [comment]
Closing this since we have a new validation solution.
